{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "reportportal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.global.serviceAccount.annotations }}
    annotations:
      {{- range $key, $value := .Values.global.serviceAccount.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
{{- end }}