apiVersion: v2
appVersion: "24.1"
description: ReportPortal.io AI-powered Test Automation Dashboard
name: reportportal
version: 24.1.4
sources:
  - https://github.com/reportportal/kubernetes
keywords:
  - reportportal
maintainers:
  - name: reportportal
    email: support@reportportal.io

# If you update dependencies version, please update also *.image.tag in values.yaml
dependencies:
  - name: postgresql
    version: 15.5.23
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.install

  - name: rabbitmq
    version: 14.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.install

  - name: opensearch
    version: 2.22.1
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.install

  - name: minio
    version: 14.7.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.install
