apiVersion: v1
kind: Service
metadata:
  name: {{ include "reportportal.fullname" . }}-index
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    service: {{ $.Values.serviceindex.name | default "index" }}
    infoEndpoint: "/info"
    healthEndpoint: "/health"
    {{- if eq .Values.ingress.class "alb" }}
    # ALB health check annotations
    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.ingress.path }}/health"
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    {{- end }}
    {{- with .Values.serviceindex.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.serviceindex.service.type | default "ClusterIP" }}
  ports:
  - name: {{ $.Values.serviceindex.service.portName | default "headless" }}
    port: 8080
    protocol: TCP
    targetPort: 8080
{{- if and (or (eq .Values.serviceindex.service.type "NodePort") (eq .Values.serviceindex.service.type "LoadBalancer")) (not (empty .Values.serviceindex.service.nodePort)) }}
    nodePort: {{ .Values.serviceindex.service.nodePort }}
{{- end }}
{{- if .Values.serviceindex.service.extraPorts }}
  {{ toYaml .Values.serviceindex.service.extraPorts | indent 2 }}
{{- end }}
  selector:
    component: {{ include "reportportal.fullname" . }}-index