apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reportportal.fullname" . }}-jobs
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.servicejobs.replicaCount | default 1 }}
  selector:
    matchLabels:
      component: {{ include "reportportal.fullname" . }}-jobs
  template:
    metadata:
      labels:
        component: {{ include "reportportal.fullname" . }}-jobs
      annotations:
        {{- range $key, $value := .Values.servicejobs.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      initContainers:
      {{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      containers:
      - env:
{{- if .Values.servicejobs.extraEnvs }}
{{ toYaml .Values.servicejobs.extraEnvs | indent 8 }}
{{- end }}
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanAttachmentCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanLogCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanLaunchCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON
          value: "{{ .Values.servicejobs.coreJobs.cleanStorageCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON
          value: "{{ .Values.servicejobs.coreJobs.storageProjectCron }}"
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE
          value: "{{ .Values.servicejobs.chunksize }}"
        {{- if .Values.servicejobs.jvmArgs }}
        - name: JAVA_OPTS
          value: "{{ .Values.servicejobs.jvmArgs }}"
        {{- end }}
        - name: RP_AMQP_HOST
          value: "{{ .Values.rabbitmq.endpoint.address }}"
        - name: RP_AMQP_PORT
          value: "{{ .Values.rabbitmq.endpoint.port }}"
        - name: RP_AMQP_ANALYZER-VHOST
          value: "{{ .Values.rabbitmq.vhost }}"
        - name: RP_AMQP_USER
          value: "{{ .Values.rabbitmq.endpoint.user }}"
        - name: RP_AMQP_PASS
        {{ if .Values.rabbitmq.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.rabbitmq.SecretName }}"
              key: "rabbitmq-password"
        {{ else }}
          value: "{{ .Values.rabbitmq.endpoint.password }}"
        {{ end }}
        - name: RP_AMQP_APIPORT
          value: "{{ .Values.rabbitmq.endpoint.apiport }}"
        - name: RP_AMQP_APIUSER
          value: "{{ .Values.rabbitmq.endpoint.apiuser }}"
        - name: RP_AMQP_APIPASS
        {{ if .Values.rabbitmq.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.rabbitmq.SecretName }}"
              key: "rabbitmq-password"
        {{ else }}
          value: "{{ .Values.rabbitmq.endpoint.password }}"
        {{ end }}
        - name: RP_DB_HOST
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: RP_DB_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: RP_DB_NAME
          value: "{{ .Values.postgresql.endpoint.dbName }}"
        {{- if .Values.postgresql.endpoint.connections }}
        - name: RP_DATASOURCE_MAXIMUMPOOLSIZE
          value: "{{ .Values.postgresql.endpoint.connections }}"
        {{- end }}
        - name: RP_DB_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: RP_DB_PASS
        {{- if .Values.postgresql.SecretName }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        {{ else }}
          value: "{{ .Values.postgresql.endpoint.password }}"
        {{ end }}
        {{ if .Values.minio.enabled }}
        - name: DATASTORE_TYPE
          value: "minio"
        - name: DATASTORE_MINIO_ENDPOINT
          value: "{{ .Values.minio.endpoint }}"
        {{- if .Values.minio.bucketPrefix }}
        - name: RP_BINARYSTORE_MINIO_BUCKETPREFIX
          value: "{{ .Values.minio.bucketPrefix }}"
        {{- end }}
        {{- if .Values.minio.defaultBucketName }}
        - name: RP_BINARYSTORE_MINIO_DEFAULTBUCKETNAME
          value: "{{ .Values.minio.defaultBucketName }}"
        {{- end }}
        {{- if .Values.minio.region }}
        - name: DATASTORE_MINIO_REGION
          value: "{{ .Values.minio.region }}"
        {{- end }}
        {{- if .Values.minio.secretName }}
        - name: DATASTORE_MINIO_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.minio.secretName }}"
              key: "{{ .Values.minio.accesskeyName }}"
        - name: DATASTORE_MINIO_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.minio.secretName }}"
              key: "{{ .Values.minio.secretkeyName }}"
       {{- else }}
        - name: DATASTORE_MINIO_ACCESSKEY
          value: "{{ .Values.minio.accesskey }}"
        - name: DATASTORE_MINIO_SECRETKEY
          value: "{{ .Values.minio.secretkey }}"
       {{- end }}
       {{ end }}
        - name: RP_PROCESSING_LOG_MAXBATCHSIZE
          value: "2000"
        - name: RP_PROCESSING_LOG_MAXBATCHTIMEOUT
          value: "6000"
        - name: RP_AMQP_MAXLOGCONSUMER
          value: "1"
        image: "{{ .Values.servicejobs.repository }}:{{ .Values.servicejobs.tag }}"
        name: jobs
        ports:
        - containerPort: 8686
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.servicejobs.resources.requests.cpu }}
            memory: {{ .Values.servicejobs.resources.requests.memory }}
          limits:
            cpu: {{ .Values.servicejobs.resources.limits.cpu }}
            memory: {{ .Values.servicejobs.resources.limits.memory }}
{{- if .Values.servicejobs.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.servicejobs.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
{{- end }}
      securityContext:
{{ toYaml .Values.servicejobs.securityContext | indent 8}}
      serviceAccountName: {{ .Values.servicejobs.serviceAccountName }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
